x = int(input('Введите число - x \n'))
y = int(input('Введите число - y \n'))
print(f'Сумма X и Y равна {x + y}\n')
print(f'Разность X и Y равна {x - y}\n')
print(f'Произведение X и Y равно {x * y}\n')
print(f'Результат деления X на Y равен {x / y}\n')
print(f'Остаток от деления  X на Y равен {x % y}\n')
print(f'X в степени Y равно {x ** y}\n')
